# Generated by Django 3.2 on 2021-04-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=20)),
                ('payee', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=50)),
                ('effectStartDate', models.DateField()),
                ('effectEndDate', models.DateField()),
                ('payDate', models.DateField()),
                ('note', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Catelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billitem')),
            ],
        ),
        migrations.AddField(
            model_name='billitem',
            name='categories',
            field=models.ManyToManyField(through='bills.Catelog', to='bills.Category'),
        ),
    ]
