# Generated by Django 3.2 on 2021-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='effectEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
